// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VentaPOS.Data;

#nullable disable

namespace VentaPOS.Migrations
{
    [DbContext(typeof(VentaPosContext))]
    [Migration("20250409153628_AgregarColumnaPrecioPlan")]
    partial class AgregarColumnaPrecioPlan
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UsuarioRole", b =>
                {
                    b.Property<int>("UsuarioID")
                        .HasColumnType("int");

                    b.Property<int>("RolID")
                        .HasColumnType("int");

                    b.HasKey("UsuarioID", "RolID");

                    b.HasIndex("RolID");

                    b.ToTable("UsuarioRoles", (string)null);
                });

            modelBuilder.Entity("UsuariosSuscripciones", b =>
                {
                    b.Property<int>("UsuarioID")
                        .HasColumnType("int");

                    b.Property<int>("SuscripcionID")
                        .HasColumnType("int");

                    b.HasKey("UsuarioID", "SuscripcionID");

                    b.HasIndex("SuscripcionID");

                    b.ToTable("UsuariosSuscripciones");
                });

            modelBuilder.Entity("VentaPOS.Models.Categoria", b =>
                {
                    b.Property<int>("CategoriaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CategoriaID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoriaID"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("text");

                    b.Property<string>("EmpresaRut")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("CategoriaID")
                        .HasName("PK__Categori__F353C1C53DC7F524");

                    b.HasIndex("EmpresaRut");

                    b.HasIndex(new[] { "Nombre" }, "UQ__Categori__75E3EFCF34D4F80D")
                        .IsUnique();

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("VentaPOS.Models.Cliente", b =>
                {
                    b.Property<int>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ClienteID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClienteId"));

                    b.Property<string>("Apellidos")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("EmpresaRut")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("RutCliente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("UltimaCompra")
                        .HasColumnType("datetime");

                    b.HasKey("ClienteId")
                        .HasName("PK__Clientes__71ABD0A71131B070");

                    b.HasIndex("EmpresaRut");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("VentaPOS.Models.ConfiguracionEmpresa", b =>
                {
                    b.Property<int>("ConfiguracionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ConfiguracionID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConfiguracionId"));

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("EmpresaRut")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.HasKey("ConfiguracionId")
                        .HasName("PK__Configur__9B95E0563E7C30A7");

                    b.HasIndex("EmpresaRut");

                    b.ToTable("ConfiguracionEmpresa", (string)null);
                });

            modelBuilder.Entity("VentaPOS.Models.DetallesVenta", b =>
                {
                    b.Property<int>("DetalleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DetalleID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DetalleID"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<decimal>("Descuento")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("Impuesto")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductoID")
                        .HasColumnType("int")
                        .HasColumnName("ProductoID");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("VentaID")
                        .HasColumnType("int")
                        .HasColumnName("VentaID");

                    b.HasKey("DetalleID");

                    b.HasIndex("ProductoID");

                    b.HasIndex("VentaID");

                    b.ToTable("DetallesVenta", (string)null);
                });

            modelBuilder.Entity("VentaPOS.Models.Empresa", b =>
                {
                    b.Property<string>("Rut")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<bool?>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<byte[]>("Contraseña")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime?>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("NombreEmpresa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Rut");

                    b.ToTable("Empresas");
                });

            modelBuilder.Entity("VentaPOS.Models.Inventario", b =>
                {
                    b.Property<int>("InventarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("InventarioID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InventarioId"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("EmpresaRut")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("FechaActualizacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("ProductoID")
                        .HasColumnType("int")
                        .HasColumnName("ProductoID");

                    b.Property<string>("Ubicacion")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("InventarioId")
                        .HasName("PK__Inventar__FB8A24B78F5A075C");

                    b.HasIndex("EmpresaRut");

                    b.HasIndex("ProductoID");

                    b.ToTable("Inventario", (string)null);
                });

            modelBuilder.Entity("VentaPOS.Models.Planes", b =>
                {
                    b.Property<int>("PlanID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlanID"));

                    b.Property<int?>("MaxUsuarios")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("Precio")
                        .HasColumnType("int");

                    b.HasKey("PlanID");

                    b.ToTable("Planes");
                });

            modelBuilder.Entity("VentaPOS.Models.Producto", b =>
                {
                    b.Property<int>("ProductoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ProductoID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductoID"));

                    b.Property<int>("CategoriaID")
                        .HasColumnType("int")
                        .HasColumnName("CategoriaID");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("text");

                    b.Property<string>("EmpresaRut")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UltimaActualizacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("ProductoID")
                        .HasName("PK__Producto__A430AE832C367D1B");

                    b.HasIndex("CategoriaID");

                    b.HasIndex("EmpresaRut");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("VentaPOS.Models.Roles", b =>
                {
                    b.Property<int>("RolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RolID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RolId"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("EmpresaRut")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("RolId")
                        .HasName("PK__Roles__F92302D15CC78A2C");

                    b.HasIndex("EmpresaRut");

                    b.HasIndex("Nombre", "EmpresaRut")
                        .IsUnique()
                        .HasDatabaseName("UQ__Roles__NombreEmpresa");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("VentaPOS.Models.Suscripciones", b =>
                {
                    b.Property<int>("SuscripcionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SuscripcionID"));

                    b.Property<bool>("Activa")
                        .HasColumnType("bit");

                    b.Property<string>("EmpresaRut")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("FormaPago")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("MaxUsuarios")
                        .HasColumnType("int");

                    b.Property<string>("NumeroComprobante")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Pagado")
                        .HasColumnType("bit");

                    b.Property<int>("PlanID")
                        .HasColumnType("int");

                    b.HasKey("SuscripcionID");

                    b.HasIndex("EmpresaRut");

                    b.HasIndex("PlanID");

                    b.ToTable("Suscripciones");
                });

            modelBuilder.Entity("VentaPOS.Models.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UsuarioID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioId"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<byte[]>("Contraseña")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("EmpresaRut")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("EmpresaRut");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("UsuarioId")
                        .HasName("PK__Usuarios__2B3DE798FCB1AA72");

                    b.HasIndex("EmpresaRut");

                    b.HasIndex(new[] { "Correo" }, "UQ__Usuarios__60695A19E6A6D41B")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("VentaPOS.Models.Venta", b =>
                {
                    b.Property<int>("VentaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VentaID"));

                    b.Property<int?>("ClienteID")
                        .HasColumnType("int");

                    b.Property<int?>("ClienteId")
                        .HasColumnType("int");

                    b.Property<string>("Comentarios")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal?>("Descuento")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("EmpresaRut")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("FechaVenta")
                        .HasColumnType("datetime");

                    b.Property<decimal?>("Impuestos")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MetodoPago")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NumeroFactura")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("Propina")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UsuarioID")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("VentaID");

                    b.HasIndex("ClienteID");

                    b.HasIndex("ClienteId");

                    b.HasIndex("EmpresaRut");

                    b.HasIndex("UsuarioID");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Ventas", (string)null);
                });

            modelBuilder.Entity("UsuarioRole", b =>
                {
                    b.HasOne("VentaPOS.Models.Roles", null)
                        .WithMany()
                        .HasForeignKey("RolID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_UsuarioRoles_Roles");

                    b.HasOne("VentaPOS.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_UsuarioRoles_Usuarios");
                });

            modelBuilder.Entity("UsuariosSuscripciones", b =>
                {
                    b.HasOne("VentaPOS.Models.Suscripciones", null)
                        .WithMany()
                        .HasForeignKey("SuscripcionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VentaPOS.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VentaPOS.Models.Categoria", b =>
                {
                    b.HasOne("VentaPOS.Models.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaRut")
                        .IsRequired()
                        .HasConstraintName("FK_Categorias_Empresas");

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("VentaPOS.Models.Cliente", b =>
                {
                    b.HasOne("VentaPOS.Models.Empresa", "Empresa")
                        .WithMany("Clientes")
                        .HasForeignKey("EmpresaRut")
                        .IsRequired()
                        .HasConstraintName("FK_Clientes_Empresas");

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("VentaPOS.Models.ConfiguracionEmpresa", b =>
                {
                    b.HasOne("VentaPOS.Models.Empresa", "Empresa")
                        .WithMany("ConfiguracionEmpresas")
                        .HasForeignKey("EmpresaRut")
                        .IsRequired()
                        .HasConstraintName("FK_ConfiguracionEmpresa_Empresas");

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("VentaPOS.Models.DetallesVenta", b =>
                {
                    b.HasOne("VentaPOS.Models.Producto", "Producto")
                        .WithMany("DetallesVentas")
                        .HasForeignKey("ProductoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_DetallesVenta_Productos");

                    b.HasOne("VentaPOS.Models.Venta", "Venta")
                        .WithMany("DetallesVentas")
                        .HasForeignKey("VentaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_DetallesVenta_Ventas");

                    b.Navigation("Producto");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("VentaPOS.Models.Inventario", b =>
                {
                    b.HasOne("VentaPOS.Models.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaRut")
                        .IsRequired()
                        .HasConstraintName("FK_Inventario_Empresas");

                    b.HasOne("VentaPOS.Models.Producto", "Producto")
                        .WithMany("Inventarios")
                        .HasForeignKey("ProductoID")
                        .IsRequired()
                        .HasConstraintName("FK_Inventario_Productos");

                    b.Navigation("Empresa");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("VentaPOS.Models.Producto", b =>
                {
                    b.HasOne("VentaPOS.Models.Categoria", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("CategoriaID")
                        .IsRequired()
                        .HasConstraintName("FK_Productos_Categorias");

                    b.HasOne("VentaPOS.Models.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaRut")
                        .IsRequired()
                        .HasConstraintName("FK_Productos_Empresas");

                    b.Navigation("Categoria");

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("VentaPOS.Models.Roles", b =>
                {
                    b.HasOne("VentaPOS.Models.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaRut")
                        .IsRequired()
                        .HasConstraintName("FK_Roles_Empresas");

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("VentaPOS.Models.Suscripciones", b =>
                {
                    b.HasOne("VentaPOS.Models.Empresa", "Empresa")
                        .WithMany("Suscripciones")
                        .HasForeignKey("EmpresaRut")
                        .IsRequired()
                        .HasConstraintName("FK_Suscripciones_Empresas");

                    b.HasOne("VentaPOS.Models.Planes", "Plan")
                        .WithMany("Suscripciones")
                        .HasForeignKey("PlanID")
                        .IsRequired()
                        .HasConstraintName("FK_Suscripciones_Planes");

                    b.Navigation("Empresa");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("VentaPOS.Models.Usuario", b =>
                {
                    b.HasOne("VentaPOS.Models.Empresa", "Empresa")
                        .WithMany("Usuarios")
                        .HasForeignKey("EmpresaRut")
                        .IsRequired()
                        .HasConstraintName("FK_Usuarios_Empresas");

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("VentaPOS.Models.Venta", b =>
                {
                    b.HasOne("VentaPOS.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteID");

                    b.HasOne("VentaPOS.Models.Cliente", null)
                        .WithMany("Venta")
                        .HasForeignKey("ClienteId");

                    b.HasOne("VentaPOS.Models.Empresa", "Empresa")
                        .WithMany("Venta")
                        .HasForeignKey("EmpresaRut")
                        .IsRequired();

                    b.HasOne("VentaPOS.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioID")
                        .IsRequired();

                    b.HasOne("VentaPOS.Models.Usuario", null)
                        .WithMany("Venta")
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Cliente");

                    b.Navigation("Empresa");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("VentaPOS.Models.Categoria", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("VentaPOS.Models.Cliente", b =>
                {
                    b.Navigation("Venta");
                });

            modelBuilder.Entity("VentaPOS.Models.Empresa", b =>
                {
                    b.Navigation("Clientes");

                    b.Navigation("ConfiguracionEmpresas");

                    b.Navigation("Suscripciones");

                    b.Navigation("Usuarios");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("VentaPOS.Models.Planes", b =>
                {
                    b.Navigation("Suscripciones");
                });

            modelBuilder.Entity("VentaPOS.Models.Producto", b =>
                {
                    b.Navigation("DetallesVentas");

                    b.Navigation("Inventarios");
                });

            modelBuilder.Entity("VentaPOS.Models.Usuario", b =>
                {
                    b.Navigation("Venta");
                });

            modelBuilder.Entity("VentaPOS.Models.Venta", b =>
                {
                    b.Navigation("DetallesVentas");
                });
#pragma warning restore 612, 618
        }
    }
}
